### ISSUE TITLE
Feat: update deps & migrate to SvelteKit v2

### ISSUE THREAD

**Issue by wizmer** [m93a/svelte-plotly.js#9]
Hi and thank you for this package,

I've updated my vite and sveltekit and I have this error message when building my package with `npm run build`:

```
2:32:36 AM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-plotly.js@0.3.2

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

After some investigation, I found out that the `package.json` on npm (on tag 0.3.2) is not the same as the one on Github (which is supposed to be at the same version 0.3.2).

https://github.com/m93a/svelte-plotly.js/blob/main/package.json
https://www.npmjs.com/package/svelte-plotly.js?activeTab=code

Could you push a new version to npm so that it reflects the latest `package.json` which is already on Github ?

Thank you

**Comment by cshaa** [comment]
Hey Benoit,
thanks for reporting this! The problem is not that `package.json` is on GitHub is different from NPM – stripping the `scripts` field was a feature of the old svelte-kit packager. The actual change that needs to be done is:
```diff
  "exports": {
-    ".": "./Plot.svelte"
+    ".": {
+      "svelte": "./Plot.svelte"
+    }
  }
```
This is because the library was created with a now-deprecated version of SvelteKit, and the specification for specifying exports changed. However, the current version fails to build with the up-to-date version of SvelteKit, so a migration will be needed.

I assume the warning you got isn't a blocking issue for you, so I won't get to it immediately, but I'll try to have the fix done later this week.

**Comment by wizmer** [comment]
Awesome, thank you ! :raised_hands:
